import 'models/brand.dart';
import 'models/product.dart';

const brands = [
  Brand(id: 1, name: 'Valve'),
  Brand(id: 2, name: 'Ubisoft'),
  Brand(id: 3, name: 'CD Projekt'),
  Brand(id: 4, name: 'Bethesda'),
  Brand(id: 5, name: 'OpenAI'),
  Brand(id: 6, name: 'Anthropic'),
  Brand(id: 7, name: 'Midjourney'),
  Brand(id: 8, name: 'Perplexity'),
];

const products = [
  Product(
    id: 1,
    name: 'Portal',
    sku: 'GAME-001',
    description: 'Головоломка с порталами и пространственными задачами.',
    type: ProductType.gameKey,
    brandId: 1,
    price: 29900,
    platform: 'Steam',
    region: 'Global',
  ),
  Product(
    id: 2,
    name: 'Portal 2',
    sku: 'GAME-002',
    description:
        'Продолжение головоломки с одиночным и совместным прохождением.',
    type: ProductType.gameKey,
    brandId: 1,
    price: 59900,
    platform: 'Steam',
    region: 'Global',
  ),
  Product(
    id: 3,
    name: 'Half-Life 2',
    sku: 'GAME-003',
    description: 'Научно-фантастический шутер с сюжетной кампанией.',
    type: ProductType.gameKey,
    brandId: 1,
    price: 49900,
    platform: 'Steam',
    region: 'Europe',
  ),
  Product(
    id: 4,
    name: 'Left 4 Dead 2',
    sku: 'GAME-004',
    description: 'Совместное прохождение кампаний против заражённых.',
    type: ProductType.gameKey,
    brandId: 1,
    price: 69900,
    platform: 'Steam',
    region: 'Global',
  ),
  Product(
    id: 5,
    name: 'Far Cry 5',
    sku: 'GAME-005',
    description: 'Шутер с открытым миром и совместным прохождением.',
    type: ProductType.gameKey,
    brandId: 2,
    price: 149900,
    platform: 'Ubisoft Connect',
    region: 'Europe',
  ),
  Product(
    id: 6,
    name: 'Watch Dogs 2',
    sku: 'GAME-006',
    description:
        'Приключение в открытом мире с использованием хакерских инструментов.',
    type: ProductType.gameKey,
    brandId: 2,
    price: 129900,
    platform: 'Ubisoft Connect',
    region: 'Global',
  ),
  Product(
    id: 7,
    name: 'Assassin’s Creed Origins',
    sku: 'GAME-007',
    description: 'Приключенческая игра в мире Древнего Египта.',
    type: ProductType.gameKey,
    brandId: 2,
    price: 179900,
    platform: 'Ubisoft Connect',
    region: 'Europe',
  ),
  Product(
    id: 8,
    name: 'The Witcher 3: Wild Hunt',
    sku: 'GAME-008',
    description: 'Ролевая игра о путешествиях ведьмака Геральта.',
    type: ProductType.gameKey,
    brandId: 3,
    price: 159900,
    platform: 'GOG',
    region: 'Global',
  ),
  Product(
    id: 9,
    name: 'Cyberpunk 2077',
    sku: 'GAME-009',
    description: 'Ролевая игра в футуристическом Найт-Сити.',
    type: ProductType.gameKey,
    brandId: 3,
    price: 299900,
    platform: 'GOG',
    region: 'Europe',
  ),
  Product(
    id: 10,
    name: 'The Witcher 2: Assassins of Kings',
    sku: 'GAME-010',
    description: 'Сюжетная ролевая игра с выбором решений.',
    type: ProductType.gameKey,
    brandId: 3,
    price: 79900,
    platform: 'GOG',
    region: 'Global',
  ),
  Product(
    id: 11,
    name: 'The Elder Scrolls V: Skyrim',
    sku: 'GAME-011',
    description: 'Фэнтезийная ролевая игра с открытым миром.',
    type: ProductType.gameKey,
    brandId: 4,
    price: 199900,
    platform: 'Steam',
    region: 'Global',
  ),
  Product(
    id: 12,
    name: 'DOOM Eternal',
    sku: 'GAME-012',
    description: 'Динамичный шутер с одиночной кампанией.',
    type: ProductType.gameKey,
    brandId: 4,
    price: 249900,
    platform: 'Steam',
    region: 'Europe',
  ),
  Product(
    id: 13,
    name: 'ChatGPT — 1 месяц',
    sku: 'AI-001',
    description: 'Подписка на сервис для работы с текстом и программным кодом.',
    type: ProductType.aiSubscription,
    brandId: 5,
    price: 249900,
    platform: 'ChatGPT',
    region: 'Europe',
    durationMonths: 1,
  ),
  Product(
    id: 14,
    name: 'ChatGPT — 3 месяца',
    sku: 'AI-002',
    description: 'Доступ к сервису для работы с текстом и программным кодом на три месяца.',
    type: ProductType.aiSubscription,
    brandId: 5,
    price: 699900,
    platform: 'ChatGPT',
    region: 'Europe',
    durationMonths: 3,
  ),
  Product(
    id: 15,
    name: 'ChatGPT — 6 месяцев',
    sku: 'AI-003',
    description:
        'Доступ к сервису для работы с текстом и программным кодом на полгода.',
    type: ProductType.aiSubscription,
    brandId: 5,
    price: 1299900,
    platform: 'ChatGPT',
    region: 'Europe',
    durationMonths: 6,
  ),
  Product(
    id: 16,
    name: 'ChatGPT — 12 месяцев',
    sku: 'AI-004',
    description:
        'Доступ к сервису для работы с текстом и программным кодом на год.',
    type: ProductType.aiSubscription,
    brandId: 5,
    price: 2399900,
    platform: 'ChatGPT',
    region: 'Europe',
    durationMonths: 12,
  ),
  Product(
    id: 17,
    name: 'Claude — 1 месяц',
    sku: 'AI-005',
    description:
        'Подписка на сервис для анализа документов и подготовки текстов.',
    type: ProductType.aiSubscription,
    brandId: 6,
    price: 259900,
    platform: 'Claude',
    region: 'Europe',
    durationMonths: 1,
  ),
  Product(
    id: 18,
    name: 'Claude — 3 месяца',
    sku: 'AI-006',
    description: 'Доступ к сервису для анализа документов на три месяца.',
    type: ProductType.aiSubscription,
    brandId: 6,
    price: 729900,
    platform: 'Claude',
    region: 'Europe',
    durationMonths: 3,
  ),
  Product(
    id: 19,
    name: 'Claude — 12 месяцев',
    sku: 'AI-007',
    description: 'Доступ к сервису для анализа документов на год.',
    type: ProductType.aiSubscription,
    brandId: 6,
    price: 2499900,
    platform: 'Claude',
    region: 'Europe',
    durationMonths: 12,
  ),
  Product(
    id: 20,
    name: 'Midjourney — 1 месяц',
    sku: 'AI-008',
    description:
        'Подписка на сервис создания изображений по текстовому описанию.',
    type: ProductType.aiSubscription,
    brandId: 7,
    price: 149900,
    platform: 'Midjourney',
    region: 'Europe',
    durationMonths: 1,
  ),
  Product(
    id: 21,
    name: 'Midjourney — 3 месяца',
    sku: 'AI-009',
    description: 'Доступ к генерации изображений на три месяца.',
    type: ProductType.aiSubscription,
    brandId: 7,
    price: 399900,
    platform: 'Midjourney',
    region: 'Europe',
    durationMonths: 3,
  ),
  Product(
    id: 22,
    name: 'Midjourney — 12 месяцев',
    sku: 'AI-010',
    description: 'Доступ к генерации изображений на год.',
    type: ProductType.aiSubscription,
    brandId: 7,
    price: 1499900,
    platform: 'Midjourney',
    region: 'Europe',
    durationMonths: 12,
  ),
  Product(
    id: 23,
    name: 'Perplexity — 1 месяц',
    sku: 'AI-011',
    description: 'Подписка на сервис поиска информации с ответами на вопросы.',
    type: ProductType.aiSubscription,
    brandId: 8,
    price: 229900,
    platform: 'Perplexity',
    region: 'Europe',
    durationMonths: 1,
  ),
  Product(
    id: 24,
    name: 'Perplexity — 12 месяцев',
    sku: 'AI-012',
    description: 'Доступ к сервису поиска информации на год.',
    type: ProductType.aiSubscription,
    brandId: 8,
    price: 2199900,
    platform: 'Perplexity',
    region: 'Europe',
    durationMonths: 12,
  ),
];
